from .application_investors import *  # noqa
from .application_partners import *  # noqa
from .company_info import *  # noqa
from .contacs import *  # noqa
from .faq import *  # noqa
from .investors import *  # noqa
from .news import *  # noqa
from .partners import *  # noqa
from .services import *  # noqa
